# This is a basic workflow to help you get started with Actions
name: Setup Clojure
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:  
  linux-static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: get graal
        run: |
          chmod u+x scripts/get-graal && scripts/get-graal
        shell: bash
  

      - name: activate graal
        run: |
          chmod u+x scripts/activate-graal && scripts/activate-graal
        shell: bash
        
      - name: install clojure
        run: chmod u+x scripts/install-clojure && scripts/install-clojure
        shell: bash

      - name: install native dev tools
        run: |
          sudo apt-get update
          sudo apt-get -y install curl unzip gcc g++ build-essential zlib1g-dev libsnappy-dev
        shell: bash

      - name: compile
        run: chmod u+x scripts/compile && scripts/compile
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: ds-graal
          path: ds-graal

